### ISSUE TITLE
Attribute 'lib' is missing when building the SD-image

### ISSUE THREAD

**Issue by MarekPasnikowski** [Thra11/nixpkgs-overlays-rk3399#4]
```
$ nix-build '<nixpkgs/nixos>' -I nixos-config=./sd-image-pinebook-pro.nix -A config.system.build.sdImage
error: attribute 'lib' missing, at /home/marek/nixpkgs-overlays-rk3399/pkgs/ap6256-firmware/default.nix:21:15
(use '--show-trace' to show detailed location information)
```

I am not proficient enough in Nix to understand, what I need to fix here.

**Comment by Thra11** [comment]
`lib` used to be part of `stdenv`. Then it was moved out and `stdenv.lib` was deprecated (so you'd get a warning), now in unstable after the 21.05 release, it's an error. You can fix it by changing any occurrences of `stdenv.lib` to just `lib`.
